"""Fact Checker agent.

Runs after synthesis in research/plan modes. Extracts 3-5 specific, verifiable
claims from the answer and cross-references each against the raw search data
(no additional API calls — purely LLM reasoning over existing evidence).

Returns a structured list of verified / uncertain / contradicted claims that
the UI surfaces as a trust signal below the answer.
"""

import logging
from typing import Literal

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from app.config import settings
from app.llm import get_llm
from app.state import AgentState

logger = logging.getLogger(__name__)

FACT_CHECKER_SYSTEM_PROMPT = """You are the Fact Checker in an AI research workspace.

You will be given:
1. An answer generated by the Research Agent.
2. The raw source material it was based on.

Your job: extract the 3–5 most important *specific* factual claims from the
answer and verify each one against the source material.

Status definitions:
  verified      — the source material clearly and directly supports this claim.
  uncertain     — the source mentions it with caveats, outdated data, or
                  indirectly implies it without a clear statement.
  contradicted  — the source material contradicts the claim OR the claim makes
                  a specific assertion that is not present anywhere in the sources.

Focus on verifiable specifics (numbers, names, dates, events, amounts) —
not opinions, analyses, or general descriptions.

Output a JSON object with this schema:
{
  "checks": [
    {"claim": "...", "status": "verified|uncertain|contradicted", "note": "..."},
    ...
  ]
}

"note" must be ≤12 words explaining the evidence or lack thereof.
Output ONLY the JSON. No extra text."""


class FactItem(BaseModel):
    claim: str = Field(description="The specific factual claim being verified.")
    status: Literal["verified", "uncertain", "contradicted"]
    note: str = Field(description="Evidence note, max 12 words.")


class FactCheckOutput(BaseModel):
    checks: list[FactItem] = Field(default_factory=list)


def fact_checker_node(state: AgentState) -> dict:
    if settings.mock_mode:
        return {
            "fact_check_results": [
                {"claim": "Revenue grew 30% YoY", "status": "verified", "note": "Confirmed in Q4 earnings report"},
                {"claim": "$500M funding round", "status": "uncertain", "note": "Source cites range, not exact figure"},
                {"claim": "2,000 employees", "status": "contradicted", "note": "Source states 1,800 as of last filing"},
            ]
        }

    messages = state.get("messages", [])
    if not messages:
        return {"fact_check_results": []}

    synthesis = messages[-1].content
    raw = state.get("raw_research", "")

    if not raw:
        return {"fact_check_results": []}

    # Truncate raw research to keep the call fast and cheap.
    raw_trimmed = raw[:2500]

    llm = get_llm(temperature=0).with_structured_output(FactCheckOutput)
    try:
        result: FactCheckOutput = llm.invoke([
            SystemMessage(content=FACT_CHECKER_SYSTEM_PROMPT),
            HumanMessage(content=(
                f"Answer to fact-check:\n{synthesis}\n\n"
                f"Source material:\n{raw_trimmed}"
            )),
        ])
        checks = [c.model_dump() for c in result.checks]
    except Exception:
        logger.exception("fact_checker structured output failed")
        checks = []

    logger.info(f"fact_checker claims={len(checks)}")
    return {"fact_check_results": checks}
